// This all came from https://loremipsum.io/
var lorem = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet id donec ultrices tincidunt arcu. Mattis molestie a iaculis at erat pellentesque. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Aenean sed adipiscing diam donec adipiscing tristique risus nec. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Non blandit massa enim nec dui nunc mattis enim ut. Varius sit amet mattis vulputate enim nulla. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Dui faucibus in ornare quam. Lectus mauris ultrices eros in cursus turpis. Dictum non consectetur a erat nam at lectus urna. Ut eu sem integer vitae justo eget magna fermentum.",
    "Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Nam aliquam sem et tortor consequat id porta. Nec feugiat in fermentum posuere. Cras fermentum odio eu feugiat. Sapien nec sagittis aliquam malesuada bibendum arcu. Quis hendrerit dolor magna eget est lorem. Mauris rhoncus aenean vel elit. Eu turpis egestas pretium aenean pharetra magna ac placerat. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Iaculis nunc sed augue lacus viverra vitae. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Vitae tortor condimentum lacinia quis vel eros donec ac. Lacinia quis vel eros donec ac odio. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum. Est sit amet facilisis magna etiam tempor. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Id nibh tortor id aliquet. Diam sit amet nisl suscipit adipiscing bibendum. Congue quisque egestas diam in arcu cursus euismod quis viverra.",
    "Gravida arcu ac tortor dignissim. Rhoncus dolor purus non enim praesent elementum facilisis leo. In massa tempor nec feugiat nisl. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Amet nisl purus in mollis nunc sed id. Pretium quam vulputate dignissim suspendisse in est ante in. Sagittis nisl rhoncus mattis rhoncus urna neque. Purus non enim praesent elementum facilisis leo vel fringilla est. Lorem ipsum dolor sit amet consectetur adipiscing. Duis convallis convallis tellus id interdum velit laoreet id donec. Augue mauris augue neque gravida in fermentum et. Vitae aliquet nec ullamcorper sit amet risus. Quam quisque id diam vel quam. Et tortor at risus viverra adipiscing at in tellus. Viverra nam libero justo laoreet sit amet cursus sit. Mattis molestie a iaculis at. Lobortis elementum nibh tellus molestie nunc non blandit massa enim.",
    "In arcu cursus euismod quis. Diam volutpat commodo sed egestas. Ac feugiat sed lectus vestibulum. Lectus sit amet est placerat in egestas erat imperdiet. Non arcu risus quis varius quam. Sed augue lacus viverra vitae congue eu consequat ac. Dui vivamus arcu felis bibendum ut tristique et. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Arcu vitae elementum curabitur vitae. Purus semper eget duis at. Arcu felis bibendum ut tristique et egestas quis. Purus ut faucibus pulvinar elementum integer enim. Nibh ipsum consequat nisl vel pretium lectus quam. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Sed enim ut sem viverra aliquet eget sit. Non diam phasellus vestibulum lorem. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. In ante metus dictum at tempor commodo ullamcorper a.",
    "Massa tincidunt dui ut ornare lectus sit amet est. Suspendisse faucibus interdum posuere lorem. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Purus in mollis nunc sed. Blandit turpis cursus in hac habitasse platea dictumst. Scelerisque purus semper eget duis at tellus at urna. Sed faucibus turpis in eu mi. Sit amet mattis vulputate enim nulla aliquet. Facilisi cras fermentum odio eu feugiat pretium nibh. Neque laoreet suspendisse interdum consectetur libero id. Morbi tristique senectus et netus et malesuada fames. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Tellus mauris a diam maecenas sed. Et sollicitudin ac orci phasellus egestas. In iaculis nunc sed augue lacus viverra vitae.",
    "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.",
    "Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.",
    "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.",
    "Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.",
    "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI."


	    ];
